title:            Yash Agarwal
description:      "Yash's Blog"
disqus_shortname: theyashagarwal

baseurl: theyashagarwal.me/
url: https://theyashagarwal.me
enforce_ssl: theyashagarwal.me

# Author information
author :
  name :           Yash Agarwal
  email :          yashagarwaljpr@gmail.com

google_analytics: "UA-75475356-1"
timezone:    Asia/Kolkata
future:      true
highlighter: rouge
line_numbers: true
#incremental: true
markdown:    kramdown
gems:
#    - jekyll-paginate
    - jekyll-gist
    - jemoji
#paginate:    4
#paginate_path: "/page:num/"

permalink:   /:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM
  hard_wrap: false

  coderay:
    coderay_line_numbers: true
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

pages_list:
  About: '/about'
  # Academics: '/academics'
  Archive: '/archive'
  Categories: '/categories'
#  Tags: '/tags'
  Almanac: '/almanac'
  CV: '/resume.pdf'
  Behind The Scenes: '/Behind_the_scenes'
  Feed: '/feed.xml'

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "/assets/scss"]
